name: Release

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app but not upload artifacts to distribution server'
        default: false
        required: false
        type: boolean
    secrets:
      GH_TOKEN:
        required: true

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  draft_release:
    permissions:
      contents: write

    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, macos-latest]
        node_version: [22]

    runs-on: ${{ matrix.os }}

    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs pull

      # 全局环境配置
      - name: Configure global settings
        run: |
          # 强制所有平台跳过 Chromium 下载
          npm config set puppeteer_skip_chromium_download true
          
          # 设置 Electron 镜像源
          npm config set electron_mirror "https://npmmirror.com/mirrors/electron/"
          
          # 设置 node-pre-gyp 镜像源
          npm config set node_pre_gyp_mirror "https://npmmirror.com/mirrors/node-pre-gyp/"

      # 跨平台缓存配置
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache/electron
            ~/.cache/node-gyp
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # macOS 专用环境配置
      - name: Setup macOS build tools
        if: matrix.os == 'macos-latest'
        run: |
          # 安装 Xcode 工具链
          sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
          sudo xcodebuild -license accept
          
          # 安装编译依赖
          brew install python3 make gcc
          
          # 配置 node-gyp 使用 Python3
          npm config set python $(which python3)
          
          # 强制 IPv4 网络
          echo "network=inet" > ~/.curlrc

      # Windows 专用环境配置
      - name: Setup Windows build tools
        if: matrix.os == 'windows-latest'
        run: |
          # 安装 Python 3 和 Visual Studio Build Tools
          choco install python --version=3.11.0
          npm install --global windows-build-tools

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      # 分步安装依赖
      - name: Install native modules (pre-cache)
        run: |
          npm install --ignore-scripts \
            active-win \
            sqlite3 \
            electron \
            node-addon-api

      - name: Install dependencies with retry
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_wait_seconds: 30
          command: npm ci --verbose

      # 后续构建步骤保持不变...
      - name: Create .env.production.local
        run: |
          echo "VITE_APP_API=${{ secrets.VITE_APP_API }}" > .env.production.local
          echo "VITE_START_PAGE_URL=${{ secrets.VITE_START_PAGE_URL }}" >> .env.production.local

      - name: Install Apple certificates
        if: matrix.os == 'macos-latest'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          mkdir -p ~/certificates
          echo $BUILD_CERTIFICATE_BASE64 | base64 --decode > ~/certificates/certificate.p12
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -t 3600 -l ~/Library/Keychains/build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security import ~/certificates/certificate.p12 -k build.keychain -P "$P12_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Build Project
        run: |
          npm run build
          ls -la packages/main/dist/
          ls -la packages/preload/dist/
          ls -la packages/renderer/dist/

      - name: Build and Publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            npx electron-builder --config .electron-builder.config.js --publish always --win
          else
            npx electron-builder --config .electron-builder.config.js --publish always
          fi

      - name: Retry artifacts upload
        uses: nick-fields/retry@v2
        with:
          timeout_minutes: 15
          max_attempts: 6
          retry_wait_seconds: 15
          command: npx electron-builder --config .electron-builder.config.js --publish ${{ inputs.dry-run && 'never' || 'always' }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}